# Generated by Django 4.2.2 on 2023-07-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_materia_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='descripcion',
            field=models.CharField(default='', max_length=100),
        ),
    ]
