# Generated by Django 4.2.2 on 2023-07-12 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_tema_alumnos_materia_alumnos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tema',
            name='descripcion',
        ),
    ]
