# Generated by Django 4.2.2 on 2023-07-13 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_tema_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('Teórico', 'Teórico'), ('Práctico', 'Práctico'), ('Mixto', 'Mixto')], max_length=50)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tema')),
            ],
        ),
    ]
