# Generated by Django 4.2.2 on 2023-07-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_subtemas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtemas',
            name='descripcion',
            field=models.CharField(default='', max_length=200),
        ),
    ]
