# Generated by Django 4.2.2 on 2023-07-13 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_subtemas_descripcion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subtemas',
            new_name='Subtema',
        ),
    ]
