# Generated by Django 4.2.2 on 2023-08-12 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_subtemas_subtema'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='initial_test',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CuestionarioInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_experiencia', models.CharField(choices=[('Principiante', 'Principiante'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], max_length=20)),
                ('estilo_aprendizaje', models.CharField(choices=[('Visual', 'Visual'), ('Auditivo', 'Auditivo'), ('Kinestésico', 'Kinestésico')], max_length=20)),
                ('contenido_preferido', models.CharField(choices=[('Videos', 'Videos'), ('Lecturas', 'Lecturas'), ('Prácticas', 'Prácticas')], max_length=20)),
                ('horarios_estudio', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], max_length=20)),
                ('duracion_sesiones', models.CharField(choices=[('Cortas', 'Cortas'), ('Moderadas', 'Moderadas'), ('Largas', 'Largas')], max_length=20)),
                ('formato_evaluacion', models.CharField(choices=[('Cuestionarios', 'Cuestionarios'), ('Proyectos', 'Proyectos'), ('Discusiones', 'Discusiones')], max_length=20)),
                ('recibir_recomendaciones', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
