# Generated by Django 4.2.2 on 2023-09-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_customuser_initial_test_cuestionarioinicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtema',
            name='tipo',
            field=models.CharField(choices=[('Matarial didáctico', 'Matarial didáctico'), ('Evaluación', 'Evaluación')], max_length=50),
        ),
    ]
