# Generated by Django 4.2.2 on 2023-09-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_subtema_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtema',
            name='tipo',
            field=models.CharField(choices=[('Material didáctico', 'Material didáctico'), ('Evaluación', 'Evaluación')], max_length=50),
        ),
    ]
