# Generated by Django 4.2.2 on 2023-09-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_subtema_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtema',
            name='tipo',
            field=models.CharField(choices=[('Material didáctico', 'Material didáctico'), ('Evaluación', 'Evaluación'), ('Video', 'Video')], max_length=50),
        ),
    ]
