# Generated by Django 4.2.2 on 2023-09-25 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtemadoc',
            name='file',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
