# Generated by Django 4.2.2 on 2023-10-01 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_subtemadoc_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroTiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_dedicado', models.PositiveIntegerField(default=0)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subtema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subtema')),
            ],
        ),
    ]
